# Generated by Django 3.2.7 on 2024-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
