# Generated by Django 3.2.7 on 2024-12-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='image',
        ),
    ]
